import { generatePayslipPDF } from "./pdfService.js";

// NOTE: kept as a separate file to avoid touching large existing pdfService.js.
// Generates a simple invoice PDF using pdfkit (same dependency as pdfService).
import PDFDocument from "pdfkit";

function createDoc() {
  return new PDFDocument({ margin: 50, size: "A4" });
}

function bufferFromDoc(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data", chunk => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", err => reject(err));
  });
}

function header(doc, title, subtitle = "") {
  doc
    .fontSize(22).font("Helvetica-Bold").text("Workforce360", 50, 50)
    .fontSize(11).font("Helvetica").fillColor("#555555")
    .text("Human Resource Management System", 50, 78)
    .moveTo(50, 100).lineTo(545, 100).strokeColor("#cccccc").stroke()
    .fillColor("#000000")
    .fontSize(16).font("Helvetica-Bold").text(title, 50, 115)
    .fontSize(11).font("Helvetica");

  if (subtitle) {
    doc.fillColor("#444444").text(subtitle, 50, 138).fillColor("#000000");
  }
}

function sectionTitle(doc, text) {
  const y = doc.y + 16;
  doc
    .fontSize(12).font("Helvetica-Bold")
    .fillColor("#1a1a2e")
    .text(text, 50, y)
    .moveTo(50, doc.y + 2).lineTo(545, doc.y + 2)
    .strokeColor("#1a1a2e").stroke()
    .fillColor("#000000")
    .font("Helvetica").fontSize(11)
    .moveDown(0.5);
}

function row(doc, label, value, y) {
  doc
    .fontSize(11).font("Helvetica-Bold").text(label, 60, y)
    .font("Helvetica").text(String(value ?? "—"), 260, y);
}

function footerLine(doc) {
  const bottom = doc.page.height - 60;
  doc
    .moveTo(50, bottom).lineTo(545, bottom).strokeColor("#cccccc").stroke()
    .fontSize(9).fillColor("#888888")
    .text(`Generated by Workforce360 on ${new Date().toLocaleString()}`, 50, bottom + 8, { align: "center" });
}

function fmtDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString();
  } catch {
    return "—";
  }
}

export async function generateInvoicePDF(invoice, freelancer, project) {
  const doc = createDoc();
  const finish = bufferFromDoc(doc);

  const invoiceNumber = invoice?.invoiceNumber || invoice?._id?.toString()?.slice(-6)?.toUpperCase() || "DRAFT";

  header(doc, "Invoice", `Invoice #${invoiceNumber}`);

  sectionTitle(doc, "Bill To");
  let y = doc.y;
  row(doc, "Freelancer", freelancer?.userId?.name || freelancer?.name || "—", y); y += 20;
  row(doc, "Email", freelancer?.userId?.email || freelancer?.email || "—", y); y += 20;

  doc.y = y + 10;

  sectionTitle(doc, "Project");
  y = doc.y;
  row(doc, "Project Name", project?.name || invoice?.project?.name || "—", y); y += 20;

  doc.y = y + 10;

  sectionTitle(doc, "Invoice Details");
  y = doc.y;
  row(doc, "Issue Date", fmtDate(invoice?.issueDate || invoice?.createdAt), y); y += 20;
  row(doc, "Due Date", fmtDate(invoice?.dueDate), y); y += 20;
  row(doc, "Status", invoice?.status || "PENDING", y); y += 20;
  row(doc, "Total Hours", invoice?.totalHours ?? invoice?.hours ?? 0, y); y += 20;
  row(doc, "Amount", `NPR ${Number(invoice?.amount ?? 0).toLocaleString()}`, y); y += 20;

  doc.y = y + 10;

  footerLine(doc);
  doc.end();
  return finish;
}

