/**
 * PDF Generation Service
 * Uses pdfkit to generate:
 *   - Employee payslips
 *   - Attendance reports
 *   - Performance/analytics reports
 *
 * Every function returns a Promise<Buffer> so controllers can
 * pipe or send the bytes directly.
 */

import PDFDocument from "pdfkit";

// ── Helpers ───────────────────────────────────────────────────────────────────

function createDoc() {
  return new PDFDocument({ margin: 50, size: "A4" });
}

function bufferFromDoc(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data",  chunk => chunks.push(chunk));
    doc.on("end",   ()    => resolve(Buffer.concat(chunks)));
    doc.on("error", err   => reject(err));
  });
}

function header(doc, title, subtitle = "") {
  doc
    .fontSize(22).font("Helvetica-Bold").text("Workforce360", 50, 50)
    .fontSize(11).font("Helvetica").fillColor("#555555")
    .text("Human Resource Management System", 50, 78)
    .moveTo(50, 100).lineTo(545, 100).strokeColor("#cccccc").stroke()
    .fillColor("#000000")
    .fontSize(16).font("Helvetica-Bold").text(title, 50, 115)
    .fontSize(11).font("Helvetica");

  if (subtitle) {
    doc.fillColor("#444444").text(subtitle, 50, 138).fillColor("#000000");
  }
}

function sectionTitle(doc, text) {
  const y = doc.y + 16;
  doc
    .fontSize(12).font("Helvetica-Bold")
    .fillColor("#1a1a2e")
    .text(text, 50, y)
    .moveTo(50, doc.y + 2).lineTo(545, doc.y + 2)
    .strokeColor("#1a1a2e").stroke()
    .fillColor("#000000").font("Helvetica").fontSize(11)
    .moveDown(0.5);
}

function row(doc, label, value, y) {
  doc
    .fontSize(11).font("Helvetica-Bold").text(label, 60, y)
    .font("Helvetica").text(String(value), 260, y);
}

function footerLine(doc) {
  const bottom = doc.page.height - 60;
  doc
    .moveTo(50, bottom).lineTo(545, bottom).strokeColor("#cccccc").stroke()
    .fontSize(9).fillColor("#888888")
    .text(
      `Generated by Workforce360 on ${new Date().toLocaleString()}`,
      50, bottom + 8, { align: "center" }
    );
}

// ── Payslip PDF ───────────────────────────────────────────────────────────────

/**
 * Generate a payslip PDF for one payroll record.
 *
 * @param {Object} payroll   Payroll document (populated with employee)
 * @param {Object} employee  Employee document (populated with userId)
 * @returns {Promise<Buffer>}
 */
export async function generatePayslipPDF(payroll, employee) {
  const doc    = createDoc();
  const finish = bufferFromDoc(doc);

  const empName  = employee?.userId?.name  || "N/A";
  const empEmail = employee?.userId?.email || "N/A";
  const empCode  = employee?.employeeCode  || "N/A";
  const dept     = employee?.department?.name || "N/A";
  const desig    = employee?.designation?.title || "N/A";

  header(doc, "Payslip", `Pay Period: ${payroll.month}`);

  // ── Employee details ───────────────────────────────────────────────────────
  sectionTitle(doc, "Employee Information");

  let y = doc.y;
  row(doc, "Employee Name",  empName,  y);       y += 20;
  row(doc, "Employee Code",  empCode,  y);       y += 20;
  row(doc, "Email",          empEmail, y);       y += 20;
  row(doc, "Department",     dept,     y);       y += 20;
  row(doc, "Designation",    desig,    y);       y += 20;
  row(doc, "Pay Month",      payroll.month, y);  y += 20;
  row(doc, "Payroll Number", payroll.payrollNumber || "N/A", y); y += 20;

  doc.y = y + 10;

  // ── Earnings ───────────────────────────────────────────────────────────────
  sectionTitle(doc, "Earnings");

  y = doc.y;
  row(doc, "Gross Salary",  `NPR ${payroll.grossSalary?.toLocaleString() ?? 0}`, y); y += 20;
  doc.y = y + 6;

  // ── Deductions breakdown ───────────────────────────────────────────────────
  sectionTitle(doc, "Deductions");

  const bd = payroll.breakdown || {};
  y = doc.y;
  row(doc, "Loss of Pay Deduction", `NPR ${bd.lopDeduction?.toLocaleString()  ?? 0}`, y); y += 20;
  row(doc, "Tax (10%)",             `NPR ${bd.taxDeduction?.toLocaleString()   ?? 0}`, y); y += 20;
  row(doc, "Total Deductions",      `NPR ${payroll.deductions?.toLocaleString() ?? 0}`, y); y += 20;
  doc.y = y + 6;

  // ── Attendance summary ─────────────────────────────────────────────────────
  sectionTitle(doc, "Attendance Summary");

  y = doc.y;
  row(doc, "Total Days in Month", bd.totalDaysInMonth ?? "—", y); y += 20;
  row(doc, "Days Attended",       bd.daysAttended     ?? "—", y); y += 20;
  row(doc, "Leave Days (Paid)",   bd.leaveDays        ?? "—", y); y += 20;
  row(doc, "Loss of Pay Days",    bd.lopDays          ?? "—", y); y += 20;
  row(doc, "Late Arrivals",       bd.lateDays         ?? "—", y); y += 20;
  row(doc, "Late Minutes",        bd.lateMinutes      ?? "—", y); y += 20;
  row(doc, "Overtime Hours",      bd.overtimeHours    ?? "—", y); y += 20;
  doc.y = y + 6;

  // ── Net salary ─────────────────────────────────────────────────────────────
  const netY = doc.y + 10;
  doc
    .rect(50, netY, 495, 34).fillColor("#1a1a2e").fill()
    .fillColor("#ffffff").fontSize(13).font("Helvetica-Bold")
    .text("NET SALARY", 60, netY + 10)
    .text(`NPR ${payroll.netSalary?.toLocaleString() ?? 0}`, 260, netY + 10)
    .fillColor("#000000").font("Helvetica");

  doc.y = netY + 50;

  footerLine(doc);
  doc.end();
  return finish;
}

// ── Attendance Report PDF ─────────────────────────────────────────────────────

/**
 * Generate an attendance report PDF.
 *
 * @param {Object[]} records   Attendance documents (plain objects)
 * @param {Object}   summary   { employeeId, period, presentDays, completedDays, totalHoursWorked, avgHoursPerDay }
 * @param {string}   empName   Employee display name
 * @returns {Promise<Buffer>}
 */
export async function generateAttendanceReportPDF(records, summary, empName = "Employee") {
  const doc    = createDoc();
  const finish = bufferFromDoc(doc);

  header(doc, "Attendance Report", `${empName}  —  Period: ${summary.period}`);

  // ── Summary cards ──────────────────────────────────────────────────────────
  sectionTitle(doc, "Monthly Summary");

  let y = doc.y;
  row(doc, "Total Records",      summary.totalDays       ?? records.length, y); y += 20;
  row(doc, "Days Present",       summary.presentDays     ?? "—",            y); y += 20;
  row(doc, "Full Days (in+out)", summary.completedDays   ?? "—",            y); y += 20;
  row(doc, "Total Hours Worked", `${summary.totalHoursWorked ?? 0} hrs`,    y); y += 20;
  row(doc, "Avg Hours / Day",    `${summary.avgHoursPerDay  ?? 0} hrs`,     y); y += 20;
  doc.y = y + 10;

  // ── Daily records table ────────────────────────────────────────────────────
  sectionTitle(doc, "Daily Records");

  // Table header
  y = doc.y + 4;
  doc
    .rect(50, y, 495, 20).fillColor("#1a1a2e").fill()
    .fillColor("#ffffff").fontSize(10).font("Helvetica-Bold")
    .text("Date",       60,  y + 5)
    .text("Clock In",   180, y + 5)
    .text("Clock Out",  300, y + 5)
    .text("Hours",      420, y + 5)
    .fillColor("#000000").font("Helvetica");

  y += 22;

  records.forEach((r, i) => {
    if (y > doc.page.height - 100) {
      doc.addPage();
      y = 50;
    }

    const bg = i % 2 === 0 ? "#f9f9f9" : "#ffffff";
    doc.rect(50, y, 495, 18).fillColor(bg).fill().fillColor("#000000");

    const date    = r.date     ? new Date(r.date).toLocaleDateString()              : "—";
    const clockIn = r.clockIn  ? new Date(r.clockIn).toLocaleTimeString()           : "—";
    const clockOut= r.clockOut ? new Date(r.clockOut).toLocaleTimeString()          : "—";
    const hours   = r.clockIn && r.clockOut
      ? `${+((new Date(r.clockOut) - new Date(r.clockIn)) / 36e5).toFixed(2)} hrs`
      : "—";

    doc.fontSize(10)
      .text(date,     60,  y + 4)
      .text(clockIn,  180, y + 4)
      .text(clockOut, 300, y + 4)
      .text(hours,    420, y + 4);

    y += 18;
  });

  doc.y = y + 10;
  footerLine(doc);
  doc.end();
  return finish;
}

// ── Performance / Analytics Report PDF ───────────────────────────────────────

/**
 * Generate a performance report PDF for an individual user.
 *
 * @param {Object} insights   Output of getProductivityInsights controller data
 * @param {string} userName
 * @returns {Promise<Buffer>}
 */
export async function generatePerformanceReportPDF(insights, userName = "User") {
  const doc    = createDoc();
  const finish = bufferFromDoc(doc);

  header(
    doc,
    "Performance Report",
    `${userName}  —  Period: ${insights.period}`
  );

  // ── Score summary ──────────────────────────────────────────────────────────
  sectionTitle(doc, "Performance Score");

  const scorePercent = Math.round((insights.performanceScore || 0) * 100);
  let y = doc.y;

  // Score bar background
  doc.rect(60, y, 400, 22).fillColor("#e0e0e0").fill();
  doc.rect(60, y, Math.round(400 * (insights.performanceScore || 0)), 22)
    .fillColor(scorePercent >= 80 ? "#2ecc71" : scorePercent >= 60 ? "#f39c12" : "#e74c3c")
    .fill();
  doc.fillColor("#000000").fontSize(11).font("Helvetica-Bold")
    .text(`${scorePercent} / 100`, 470, y + 5);

  y += 32;
  doc.font("Helvetica").fontSize(10).fillColor("#444444")
    .text(insights.insight || "", 60, y, { width: 430 });
  doc.fillColor("#000000");
  doc.y += 10;

  // ── Components ────────────────────────────────────────────────────────────
  sectionTitle(doc, "Score Components");

  const c = insights.components || {};
  y = doc.y;
  row(doc, "Task Completion Ratio",   `${+(c.taskCompletionRatio * 100).toFixed(1)}%`, y); y += 20;
  row(doc, "Quality Score",           `${+(c.qualityScore        * 100).toFixed(1)}%`, y); y += 20;
  row(doc, "Deadline Adherence",      `${+(c.deadlineAdherence   * 100).toFixed(1)}%`, y); y += 20;
  doc.y = y + 6;

  // ── Task summary ──────────────────────────────────────────────────────────
  sectionTitle(doc, "Task Summary");

  const t = insights.taskSummary || {};
  y = doc.y;
  row(doc, "Total Tasks",       t.total          ?? "—", y); y += 20;
  row(doc, "Completed",         t.completed      ?? "—", y); y += 20;
  row(doc, "Overdue",           t.overdue        ?? "—", y); y += 20;
  row(doc, "Completion Rate",   t.completionRate ?? "—", y); y += 20;
  doc.y = y + 6;

  // ── Timesheet summary (freelancers) ───────────────────────────────────────
  const ts = insights.timesheetSummary || {};
  if (ts.totalEntries > 0) {
    sectionTitle(doc, "Timesheet Summary");

    y = doc.y;
    row(doc, "Total Hours Logged",  `${ts.totalHoursLogged ?? 0} hrs`, y); y += 20;
    row(doc, "Avg Hours / Entry",   `${ts.avgHoursPerEntry ?? 0} hrs`, y); y += 20;
    row(doc, "Total Entries",       ts.totalEntries        ?? 0,       y); y += 20;
    doc.y = y + 6;
  }

  // ── Anomaly flag ──────────────────────────────────────────────────────────
  const anomaly = insights.anomaly || {};
  if (anomaly.isAnomaly) {
    const flagColor = anomaly.flag === "EXCEPTIONAL" ? "#27ae60" : "#e74c3c";
    y = doc.y + 10;
    doc
      .rect(50, y, 495, 28).fillColor(flagColor).fill()
      .fillColor("#ffffff").fontSize(12).font("Helvetica-Bold")
      .text(`Anomaly Detected: ${anomaly.flag}  (Z-Score: ${anomaly.zScore})`, 60, y + 8)
      .fillColor("#000000").font("Helvetica");
    doc.y = y + 38;
  }

  footerLine(doc);
  doc.end();
  return finish;
}
